spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: mircoservicecloud-config-basco-dev
---
spring:
  profiles: test
    application:
      name: mircoservicecloud-config-basco-test
# 请保存为UTF-8格式